### ISSUE TITLE
Usage of react-well-plates

### ISSUE THREAD

**Issue by tinanemati** [zakodium-oss/react-well-plates#26]
How can I use the react-well-plates in my project after I have installed them? Are there any instructions on how I can use the components that react-well-plates offer?

**Comment by stropitek** [comment]
Hello, there are examples of how to use the component in the "storybook":
https://zakodium-oss.github.io/react-well-plates

**Comment by tinanemati** [comment]
![Screenshot 2023-08-17 at 11 38 09 AM](https://github.com/zakodium-oss/react-well-plates/assets/48773069/37c73ea7-35ac-487e-8330-4c84dc32e32d)
I'm having problems opening the "storybook"

**Comment by tinanemati** [comment]
@stropitek

**Comment by stropitek** [comment]
Thank you I just fixed it.
